name: Characters processor

on:
  workflow_call:
    inputs:
      characters:
        description: "Characters mapping (YAML string)"
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout smash-bros-pimp-readme
        uses: actions/checkout@v4
        with:
          repository: enzodeg40/smash-bros-pimp-readme
          path: smash-bros-pimp-readme

      - name: Checkout calling repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: target-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install deps
        run: |
          pip install -r smash-bros-pimp-readme/requirements.txt

      - name: Run script
        env:
          CHARACTERS: ${{ inputs.characters }}
        run: |
          cd smash-bros-pimp-readme
          python src/main.py

      - name: Commit and push changes
        run: |
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "Update README with character renders"
          git push
